import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import { Sun, Moon } from "lucide-react"
import { MoonIcon } from "@heroicons/react/24/solid";
import { Boldonse } from "next/font/google";
import { ThemeToggle } from "../components/themeToggle";
import { VisitCount } from "../components/VisitCount";
import { Roboto_Mono } from "next/font/google";
import Script from "next/script";


const boldonse = Boldonse({
  subsets: ["latin"],
  weight: "400",
});

const RobotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});


const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "André Pieri — Full Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-br"
      data-theme="dark"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${RobotoMono.variable} antialiased`}
    >
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {`(function(){try{var m=window.matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.setAttribute("data-theme",m?"dark":"light")}catch(e){}})()`}
        </Script>
      </head>
      <body>
        {/* Header */}
        <header className="flex flex-shrink p-3 sm:p-3 border-b border-header-border sticky top-0 z-50 bg-background/70 backdrop-blur-xl transform-gpu">
          {/* Everything inside header */}
          <div className="max-w-[720px] mx-auto flex gap-3 sm:gap-3 items-center w-full">
            <Link href="/" className="text-base sm:text-sm font-bold mr-auto transition hover:text-semi-muted">APP</Link>
            <Link href="/projects" className="text-xs sm:text-sm text-muted hover:text-hover-muted transition-colors duration-200">Projetos</Link>
            <Link href="/experience" className="text-xs sm:text-sm text-muted hover:text-hover-muted transition-colors duration-200">Experiência</Link>
            <Link href="/technologies" className="text-xs sm:text-sm mr-2 sm:mr-3 text-muted hover:text-semi-muted transition-colors duration-200">Tecnologias</Link>
            <span className="text-xl sm:text-2xl font-thin font-geist text-muted/40 cursor-default mb-1">|</span>
            <ThemeToggle />
          </div>
        </header>
        <div className="overflow-clip">
          {children}
        </div>
        <footer className="max-w-[720px] mx-4 sm:mx-auto">
        <hr className="mt-4 text-project border-dashed mt-15 max-w-[720px] mx-auto" />
        <div>
          <div className="mt-7 text-center sm:flex sm:items-center sm:justify-center sm:gap-4">
            <div>
              <span className="italic text-[#6a7282]">Repetindo até conseguir.</span>
              <div className="flex justify-center gap-2 items-center mt-2">
                <span className="text-foreground text-[13px]">André Pieri</span>
                <span className="text-[#6a7282]/50">/</span>
                <span className="text-foreground/50 text-[13px]">Mato Grosso do Sul, Brasil</span>
              </div>
            </div>
            <div className="mt-2 sm:mt-0 flex text-[#6a7282] font-medium text-[14px] border border-project w-fit mx-auto sm:mx-0 rounded-3xl p-1 px-2 gap-1 border-dashed">
              <span>Visitado por</span>
              <VisitCount />
              <span>pessoas</span>
            </div>
          </div>
        </div>
        <div className="mb-10"></div>
        </footer>
      </body>
    </html>
  );
}
