import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import { Sun, Moon } from "lucide-react"
import { MoonIcon } from "@heroicons/react/24/solid";
import { Boldonse } from "next/font/google";
import { ThemeToggle } from "../components/themeToggle";
import { Roboto_Mono } from "next/font/google";


const boldonse = Boldonse({
  subsets: ["latin"],
  weight: "400",
});

const RobotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});


const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "André Pieri — Full Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-br"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} ${RobotoMono.variable} h-full antialiased overflow-x-hidden`}
    >
      <body className="overflow-x-hidden">
        {/* Header */}
        <header className="flex flex-shrink p-3 sm:p-3 border-b border-header-border">
          {/* Everything inside header */}
          <div className="max-w-[720px] mx-auto flex gap-3 sm:gap-3 items-center w-full">
            <Link href="/" className="text-base sm:text-sm font-bold mr-auto transition hover:text-semi-muted">APP</Link>
            <Link href="/" className="text-xs sm:text-sm text-muted hover:text-semi-muted transition-colors duration-200">Projetos</Link>
            {/* Coming Soon */}
            {/* <Link href="/" className="text-xs sm:text-sm text-muted hover:text-semi-muted transition-colors duration-200">Experiências</Link> */}
            {/* <Link href="/" className="text-xs sm:text-sm mr-2 sm:mr-3 text-muted hover:text-semi-muted transition-colors duration-200">Certificados</Link> */}
            <span className="text-xl sm:text-2xl font-thin font-geist text-muted/40 cursor-default mb-1">|</span>
            <ThemeToggle />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
